# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.3.6.3
_src_path: https://github.com/Escodoo/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: Escodoo Fleet Odoo Addons
repo_name: Fleet Addons
repo_slug: fleet-addons
travis_apt_packages: []
travis_apt_sources: []
